#!/bin/sh

# installer related
APPNAME="Health Command Center"
INSTALL_DIR="/opt/certi/command-center"
SERVICE_FILEPATH="/etc/systemd/system"
SERVICE_FILENAME="commandcenter.service"
SERVER_REQURIED_DOCKER_VERSION="1.10.3"
SERVER_REQURIED_UBUNTU_VERSION="16.04"   

DOCKERIMAGE_USER_EVENTS="health-control-room/user-events"
DOCKERCONTAINER_USER_EVENTS="user-events"
DOCKERCONTAINER_USER_EVENTS_PORT="3000"
DOCKERCONTAINER_USER_EVENTS_VOLUME_LOG="${DOCKERCONTAINER_USER_EVENTS}_log"
DOCKERCONTAINER_USER_EVENTS_RESTART="on-failure:10"

DOCKERIMAGE_USER_EVENTS_FRONTEND="health-control-room/user-events-frontend"
DOCKERCONTAINER_USER_EVENTS_FRONTEND="user-events-frontend"
DOCKERCONTAINER_USER_EVENTS_FRONTEND_PORT="8080"
DOCKERCONTAINER_USER_EVENTS_FRONTEND_VOLUME_LOG="${DOCKERCONTAINER_USER_EVENTS_FRONTEND}_log"
DOCKERCONTAINER_USER_EVENTS_FRONTEND_RESTART="on-failure:10"

DOCKERIMAGE_DASHBOARD="health-control-room/dashboard"
DOCKERCONTAINER_DASHBOARD="dashboard"
DOCKERCONTAINER_DASHBOARD_PORT="3001"
DOCKERCONTAINER_DASHBOARD_VOLUME_LOG="${DOCKERCONTAINER_DASHBOARD}_log"
DOCKERCONTAINER_DASHBOARD_RESTART="on-failure:10"

DOCKERIMAGE_DASHBOARD_FRONTEND="health-control-room/dashboard-frontend"
DOCKERCONTAINER_DASHBOARD_FRONTEND="dashboard-frontend"
DOCKERCONTAINER_DASHBOARD_FRONTEND_PORT="8081"
DOCKERCONTAINER_DASHBOARD_FRONTEND_VOLUME_LOG="${DOCKERCONTAINER_DASHBOARD_FRONTEND}_log"
DOCKERCONTAINER_DASHBOARD_FRONTEND_RESTART="on-failure:10"

DOCKERIMAGE_MONGODB="health-control-room/mongodb"
DOCKERCONTAINER_MONGODB="mongodb"
DOCKERCONTAINER_MONGODB_VOLUME_CONFIG="${DOCKERCONTAINER_MONGODB}_config"
DOCKERCONTAINER_MONGODB_VOLUME_DATA="${DOCKERCONTAINER_MONGODB}_data"
MONGODB_USER="root"
MONGODB_PWD="ilikerandompasswords"

DOCKERIMAGE_MYSQLDB="health-control-room/mysqldb"
DOCKERCONTAINER_MYSQLDB="mysqldb"
DOCKERCONTAINER_MYSQLDB_VOLUME_MYSQL="${DOCKERCONTAINER_MYSQLDB}"
DOCKERCONTAINER_MYSQLDB_ROOT_PWD="ilikerandompasswords"
OPENFIREDB_NAME="openfiredb"
OPENFIREDB_USER="openfire-user"
OPENFIREDB_PWD="ilikeopenfire"

DOCKERIMAGE_OPENFIRE="health-control-room/openfire"
DOCKERCONTAINER_OPENFIRE="openfire"
DOCKERCONTAINER_OPENFIRE_RESTART="on-failure:10"
DOCKERCONTAINER_OPENFIRE_1="9090"
DOCKERCONTAINER_OPENFIRE_2="9091"
DOCKERCONTAINER_OPENFIRE_3="7070"
DOCKERCONTAINER_OPENFIRE_4="7443"
DOCKERCONTAINER_OPENFIRE_5="5222"
DOCKERCONTAINER_OPENFIRE_6="5223"
DOCKERCONTAINER_OPENFIRE_7="5269"
DOCKERCONTAINER_OPENFIRE_8="5275"
DOCKERCONTAINER_OPENFIRE_9="5276"
DOCKERCONTAINER_OPENFIRE_10="5262"
DOCKERCONTAINER_OPENFIRE_11="5263"
DOCKERCONTAINER_OPENFIRE_12="30000"
DOCKERCONTAINER_OPENFIRE_13="30050"
DOCKERCONTAINER_OPENFIRE_PORTS="-p ${DOCKERCONTAINER_OPENFIRE_1}:${DOCKERCONTAINER_OPENFIRE_1} -p ${DOCKERCONTAINER_OPENFIRE_2}:${DOCKERCONTAINER_OPENFIRE_2} -p ${DOCKERCONTAINER_OPENFIRE_3}:${DOCKERCONTAINER_OPENFIRE_3} -p ${DOCKERCONTAINER_OPENFIRE_4}:${DOCKERCONTAINER_OPENFIRE_4} -p ${DOCKERCONTAINER_OPENFIRE_5}:${DOCKERCONTAINER_OPENFIRE_5} -p ${DOCKERCONTAINER_OPENFIRE_6}:${DOCKERCONTAINER_OPENFIRE_6} -p ${DOCKERCONTAINER_OPENFIRE_7}:${DOCKERCONTAINER_OPENFIRE_7} -p ${DOCKERCONTAINER_OPENFIRE_8}:${DOCKERCONTAINER_OPENFIRE_8} -p ${DOCKERCONTAINER_OPENFIRE_9}:${DOCKERCONTAINER_OPENFIRE_9} -p ${DOCKERCONTAINER_OPENFIRE_10}:${DOCKERCONTAINER_OPENFIRE_10} -p ${DOCKERCONTAINER_OPENFIRE_11}:${DOCKERCONTAINER_OPENFIRE_11} -p ${DOCKERCONTAINER_OPENFIRE_12}-${DOCKERCONTAINER_OPENFIRE_13}:${DOCKERCONTAINER_OPENFIRE_12}-${DOCKERCONTAINER_OPENFIRE_13}/udp"
DOCKERCONTAINER_OPENFIRE_VOLUME="${DOCKERCONTAINER_OPENFIRE}"

DOCKERIMAGE_NGINX="health-control-room/nginx"
DOCKERCONTAINER_NGINX="nginx"
DOCKERCONTAINER_NGINX_VOLUME_LOGS="${DOCKERCONTAINER_NGINX}_log"
DOCKERCONTAINER_NGINX_VOLUME_WWW="${DOCKERCONTAINER_NGINX}_www"
DOCKERCONTAINER_NGINX_PORT="2001"
DOCKERCONTAINER_NGINX_RESTART="on-failure:10"


#nothing should be exectured in this "function library" but who knows...
main() {
	echo "lib main"
}

if [ "${1}" != "--source-only" ]; then
    main "${@}"
fi